### PR TITLE
Fix compatibility with Arduino > 1.6.12

### LINKED ISSUE #159: Some changes needed for ArduinoIDE 1.6.12
Since there was a huge cleanup of the Editor code during 1.6.11 -> 1.6.12 switch, some extensions do not behave correctly anymore. Ardublock, for example, fails as reported in https://github.com/arduino/Arduino/issues/5454 . Please update the relevant code so the functionality is restored on newer IDEs (reflections may be necessary when "linking" against the newer jars)

### PR DESCRIPTION
**Pull request by facchinm**
Fixes https://github.com/taweili/ardublock/issues/159 and https://github.com/arduino/Arduino/issues/5454

### CODE REVIEW

**Comment by TonyCallear** [comment]
Thank you Martino, it was very good of you to get tis sorted and I'm sorry for the very great delay in getting this merged

**Comment by Magdalena73** [comment]
Hi!
I have installed the Arduino IDE version 1.8.2 and tried to upload an example on my Arduino UNO board using the ArduBlock, but I got just a lot of errors related to Java :
"Exception in thread "AWT-EventQueue-0" 
java.lang.NoSuchMethodError:processing.app.Editor.setText(Ljava/lang/String;) ... "
(see attached) 
error-ardublock

The IDE is working well, also the S4A scratch version for Arduino works well.
I just started learning how to use the Arduino with my daughter not long ago, I will apreciate any help. Thanks!
(I use Windows 10, 64-Bit)
Magdalena

**Comment by TonyCallear** [comment]
I'm not sure which version of ArduBlock you are using but this problem looks familiar and is fixed in the latest release here.. https://github.com/taweili/ardublock/releases

Do try that out and let us know what you think.

**Comment by Magdalena73** [comment]
Thanks so much!! it works perfect! :)

**Comment by NickCarter2** [comment]
I got same issue so I updated to latest 2017 beta.  Uploaded BLINK on 1.8.9 IDE and it
 uploaded and blinked :-D

**Pull request merged**
